# Generated by Django 3.1.3 on 2021-03-19 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='conetent',
            new_name='content',
        ),
    ]
